//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Выгр файла.
    /// </summary>
    // *** Start programmer edit section *** (ВыгрФайла CustomAttributes)

    // *** End programmer edit section *** (ВыгрФайла CustomAttributes)
    [AutoAltered()]
    [Caption("Выгр файла")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ВыгрФайлаE", new string[] {
            "ИмяФайла as \'Имя файла\'",
            "Конверт.ИмяДок",
            "Конверт"})]
    [View("ВыгрФайлаL", new string[] {
            "ИмяФайла as \'Имя файла\'",
            "Конверт.ИмяДок",
            "Конверт"})]
    public class ВыгрФайла : ICSSoft.STORMNET.DataObject
    {
        
        private string fИмяФайла;
        
        private IIS.Kursovaya1.Конверт fКонверт;
        
        // *** Start programmer edit section *** (ВыгрФайла CustomMembers)

        // *** End programmer edit section *** (ВыгрФайла CustomMembers)

        
        /// <summary>
        /// ИмяФайла.
        /// </summary>
        // *** Start programmer edit section *** (ВыгрФайла.ИмяФайла CustomAttributes)

        // *** End programmer edit section *** (ВыгрФайла.ИмяФайла CustomAttributes)
        [StrLen(255)]
        public virtual string ИмяФайла
        {
            get
            {
                // *** Start programmer edit section *** (ВыгрФайла.ИмяФайла Get start)

                // *** End programmer edit section *** (ВыгрФайла.ИмяФайла Get start)
                string result = this.fИмяФайла;
                // *** Start programmer edit section *** (ВыгрФайла.ИмяФайла Get end)

                // *** End programmer edit section *** (ВыгрФайла.ИмяФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыгрФайла.ИмяФайла Set start)

                // *** End programmer edit section *** (ВыгрФайла.ИмяФайла Set start)
                this.fИмяФайла = value;
                // *** Start programmer edit section *** (ВыгрФайла.ИмяФайла Set end)

                // *** End programmer edit section *** (ВыгрФайла.ИмяФайла Set end)
            }
        }
        
        /// <summary>
        /// Выгр файла.
        /// </summary>
        // *** Start programmer edit section *** (ВыгрФайла.Конверт CustomAttributes)

        // *** End programmer edit section *** (ВыгрФайла.Конверт CustomAttributes)
        [PropertyStorage(new string[] {
                "Конверт"})]
        [NotNull()]
        public virtual IIS.Kursovaya1.Конверт Конверт
        {
            get
            {
                // *** Start programmer edit section *** (ВыгрФайла.Конверт Get start)

                // *** End programmer edit section *** (ВыгрФайла.Конверт Get start)
                IIS.Kursovaya1.Конверт result = this.fКонверт;
                // *** Start programmer edit section *** (ВыгрФайла.Конверт Get end)

                // *** End programmer edit section *** (ВыгрФайла.Конверт Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ВыгрФайла.Конверт Set start)

                // *** End programmer edit section *** (ВыгрФайла.Конверт Set start)
                this.fКонверт = value;
                // *** Start programmer edit section *** (ВыгрФайла.Конверт Set end)

                // *** End programmer edit section *** (ВыгрФайла.Конверт Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ВыгрФайлаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВыгрФайлаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВыгрФайлаE", typeof(IIS.Kursovaya1.ВыгрФайла));
                }
            }
            
            /// <summary>
            /// "ВыгрФайлаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ВыгрФайлаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ВыгрФайлаL", typeof(IIS.Kursovaya1.ВыгрФайла));
                }
            }
        }
    }
}
