//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Загр файла.
    /// </summary>
    // *** Start programmer edit section *** (ЗагрФайла CustomAttributes)

    // *** End programmer edit section *** (ЗагрФайла CustomAttributes)
    [AutoAltered()]
    [Caption("Загр файла")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗагрФайлаE", new string[] {
            "ПутьФайла as \'Путь файла\'",
            "ЭксФайлы as \'Эксель\'",
            "ЭксФайлы.Дата as \'дата\'",
            "ЭксФайлы.Имя as \'Имя\'",
            "ЭксФайлы.Репозиторий as \'Реп\'"})]
    [MasterViewDefineAttribute("ЗагрФайлаE", "ЭксФайлы", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "")]
    [View("ЗагрФайлаL", new string[] {
            "ПутьФайла as \'Путь файла\'",
            "ЭксФайлы as \'Эксель\'",
            "ЭксФайлы.Дата as \'дата\'",
            "ЭксФайлы.Имя as \'Имя\'",
            "ЭксФайлы.Репозиторий as \'Реп\'"})]
    [MasterViewDefineAttribute("ЗагрФайлаL", "ЭксФайлы", ICSSoft.STORMNET.LookupTypeEnum.Combo, "", "")]
    public class ЗагрФайла : ICSSoft.STORMNET.DataObject
    {
        
        private string fПутьФайла;
        
        private IIS.Kursovaya1.ЭксФайлы fЭксФайлы;
        
        // *** Start programmer edit section *** (ЗагрФайла CustomMembers)

        // *** End programmer edit section *** (ЗагрФайла CustomMembers)

        
        /// <summary>
        /// ПутьФайла.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрФайла.ПутьФайла CustomAttributes)

        // *** End programmer edit section *** (ЗагрФайла.ПутьФайла CustomAttributes)
        [StrLen(255)]
        public virtual string ПутьФайла
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрФайла.ПутьФайла Get start)

                // *** End programmer edit section *** (ЗагрФайла.ПутьФайла Get start)
                string result = this.fПутьФайла;
                // *** Start programmer edit section *** (ЗагрФайла.ПутьФайла Get end)

                // *** End programmer edit section *** (ЗагрФайла.ПутьФайла Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрФайла.ПутьФайла Set start)

                // *** End programmer edit section *** (ЗагрФайла.ПутьФайла Set start)
                this.fПутьФайла = value;
                // *** Start programmer edit section *** (ЗагрФайла.ПутьФайла Set end)

                // *** End programmer edit section *** (ЗагрФайла.ПутьФайла Set end)
            }
        }
        
        /// <summary>
        /// Загр файла.
        /// </summary>
        // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы CustomAttributes)

        // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы CustomAttributes)
        [PropertyStorage(new string[] {
                "ЭксФайлы"})]
        [NotNull()]
        public virtual IIS.Kursovaya1.ЭксФайлы ЭксФайлы
        {
            get
            {
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Get start)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Get start)
                IIS.Kursovaya1.ЭксФайлы result = this.fЭксФайлы;
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Get end)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Set start)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Set start)
                this.fЭксФайлы = value;
                // *** Start programmer edit section *** (ЗагрФайла.ЭксФайлы Set end)

                // *** End programmer edit section *** (ЗагрФайла.ЭксФайлы Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗагрФайлаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗагрФайлаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗагрФайлаE", typeof(IIS.Kursovaya1.ЗагрФайла));
                }
            }
            
            /// <summary>
            /// "ЗагрФайлаL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗагрФайлаL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗагрФайлаL", typeof(IIS.Kursovaya1.ЗагрФайла));
                }
            }
        }
    }
}
