//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Kursovaya1
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Расширение.
    /// </summary>
    // *** Start programmer edit section *** (Расширение CustomAttributes)

    // *** End programmer edit section *** (Расширение CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("РасширениеE", new string[] {
            "Наименование as \'Наименование\'"})]
    [View("РасширениеL", new string[] {
            "Наименование as \'Наименование\'"})]
    public class Расширение : ICSSoft.STORMNET.DataObject
    {
        
        private string fНаименование;
        
        // *** Start programmer edit section *** (Расширение CustomMembers)

        // *** End programmer edit section *** (Расширение CustomMembers)

        
        /// <summary>
        /// Наименование.
        /// </summary>
        // *** Start programmer edit section *** (Расширение.Наименование CustomAttributes)

        // *** End programmer edit section *** (Расширение.Наименование CustomAttributes)
        [StrLen(255)]
        public virtual string Наименование
        {
            get
            {
                // *** Start programmer edit section *** (Расширение.Наименование Get start)

                // *** End programmer edit section *** (Расширение.Наименование Get start)
                string result = this.fНаименование;
                // *** Start programmer edit section *** (Расширение.Наименование Get end)

                // *** End programmer edit section *** (Расширение.Наименование Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Расширение.Наименование Set start)

                // *** End programmer edit section *** (Расширение.Наименование Set start)
                this.fНаименование = value;
                // *** Start programmer edit section *** (Расширение.Наименование Set end)

                // *** End programmer edit section *** (Расширение.Наименование Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "РасширениеE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасширениеE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасширениеE", typeof(IIS.Kursovaya1.Расширение));
                }
            }
            
            /// <summary>
            /// "РасширениеL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View РасширениеL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("РасширениеL", typeof(IIS.Kursovaya1.Расширение));
                }
            }
        }
    }
}
